#!/bin/bash
#SBATCH -N 2
# ^ number of nodes (16 cores per node)
#SBATCH -c 16
# ^ number of cores (16 per node)
#SBATCH --mem=30g
#SBATCH -p cpu
#SBATCH --qos=long-cpu
#SBATCH --job-name=LJ_dCLowT_3
#SBATCH -o ./output/dC2LowT_3.txt
#SBATCH -t 02-12:00:00
# ^ sets walltime DD-HH:MM:SS

source /etc/profile
python3 LJ3D_joined.py
