#!/bin/bash
#SBATCH -N 1
# ^ number of nodes (16 cores per node)
#SBATCH -c 16
# ^ number of cores (16 per node)
#SBATCH -p cpu
#SBATCH --qos=debug
#SBATCH --job-name=firstTestRun
#SBATCH -o ./output/debug_1.txt

source /etc/profile
python3 LJ3D_joined.py
