#!/bin/bash
#SBATCH -N 1
# ^ number of nodes (16 cores per node)
#SBATCH -c 16
# ^ number of cores (16 per node)
#SBATCH -p cpu
#SBATCH --qos=debug
#SBATCH --job-name=PetesJob
#SBATCH -o ./output/firstOutput.txt

source /etc/profile
python3 commonFunctions.py
