#!/bin/bash
#SBATCH -N 2
# ^ number of nodes (16 cores per node)
#SBATCH -c 16
# ^ number of cores (16 per node)
#SBATCH -p cpu
#SBATCH --qos=long-cpu
#SBATCH --job-name=NISTrun_redTemp085_1e7moves
#SBATCH -o ./output/NISTrun_redTemp085_1e7moves.txt
#SBATCH -t 02-00:00:00
# ^ sets walltime DD-HH:MM:SS

source /etc/profile
python3 LJ3D_joined.py
