#!/bin/bash
#SBATCH -N 2
# ^ number of nodes (16 cores per node)
#SBATCH -c 16
# ^ number of cores (16 per node)
#SBATCH -p cpu
#SBATCH --qos=long-cpu
#SBATCH --job-name=shortRun_badConvergence
#SBATCH -o ./output/shortRun_badConvergence_1.txt
#SBATCH -t 05-00:00:00
# ^ sets walltime DD-HH:MM:SS

source /etc/profile
python3 LJ3D_joined.py
