#!/bin/bash
#SBATCH -N 1
# ^ number of nodes (16 cores per node)
#SBATCH -c 16
# ^ number of cores (16 per node)
#SBATCH -p cpu
#SBATCH --qos=long-cpu
#SBATCH --job-name=debugRun2
#SBATCH -o ./output/debugRun2_1.txt
#SBATCH -t 00-12:00:00
# ^ sets walltime DD-HH:MM:SS

source /etc/profile
python3 LJ3D_joined.py
